### ISSUE TITLE
install-chef-server.sh is not creating .bash_profile

### ISSUE THREAD

**Issue by openrio** [rcbops/support-tools#13]
The install-chef-server.sh is not creating .bash_profile. After creating manually, works perfectly.

**Comment by jameswthorne** [comment]
Fixed in #14. Thanks for the heads up.

**Comment by claco** [comment]
Closing. Fixed in https://github.com/rcbops/support-tools/pull/15

**Comment by openrio** [comment]
#15 worked fine. Thank you very much.
