### ISSUE TITLE
incorrect order for commands in install-cookbooks.sh 

### ISSUE THREAD

**Issue by seaveez** [rcbops/support-tools#7]
The final two commands in the script, I think, are out of order. What's described in README is 

  knife cookbook upload -a -o cookbooks
  knife role from file roles/*.rb

Being new, I don't know if the order really makes a difference (although following the steps documented did fix my issue), at the very least, what's documented and what's in the script should be consistent.

**Comment by DavidWittman** [comment]
@seaveez Thanks for opening this issue. The order doesn't really make a difference when you're uploading the roles/cookbooks. However, for consistency's sake I'll update the install-cookbooks script to address this.
